apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator-3
spec:
  template:
    spec:
      containers:
      - name: loader
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do wget -q -O- http://nginx-deployment; done"]
      restartPolicy: Never
