apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod-3
  name: mypod-3
spec:
  tolerations:
  - key: "mysize"
    operator: "Equal"
    value: "large"
    effect: "NoSchedule"
  containers:
  - image: nginx
    name: mypod-2
    resources: {}
