apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eksadmin-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: newsa
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin-clusterrole
  apiGroup: rbac.authorization.k8s.io
